project:
  type: website

website:
  page-navigation: true
  navbar:
    right:
      - icon: house
        href: index.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Noto Serif SC"
    linestretch: 1.65
    css: styles.css


