project:
  type: website

website:
  page-navigation: true
  navbar:
    right:
      - icon: house
        href: index.qmd
      - icon: images
        href: gallery.qmd

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Noto Serif SC"
    linestretch: 1.65
    css: styles.css

