project:
  type: website

website:
  title: "一十三"
  page-navigation: true
  sidebar:
    style: "docked"
    align: "center"
    contents:
      - href: index.qmd
        text: "引"
      - section: "第一节"
        contents:
          - href: about.qmd
            text: "关于"
      
format:
  html:
    theme: [cosmo, theme.scss]
    mainfont: "Noto Serif SC"
    css: styles.css
    toc: false



