---
title: 看电影《我这一辈子》
---

看电影，《我这一辈子》1950年。  
导演、编剧、主演：石挥，话剧出身。  
原作：老舍，人民艺术家。  

初中看《祥子》，只觉得不争气，实在是旧时代。  
昨晚看《我这一辈子》，十点二十开始，看到了熄灯，没完。搬起两个小板凳，又看到深夜十二点。  
自觉，眼泪鼻涕流了满脸。合上盖子，端走小板凳，抹了把脸，上床了。  
可上床横竖也睡不着。  

想起当晚早些时候比着英文看了《狂人日记》，所谓中文第一篇白话，建国前的旧白话。真成熟。  
好也是好，只是奇怪为什么没遭禁？  
原来究竟教材老练，给扣上个“揭露封建礼教吃人本质”的帽子，这么一来，120分的文章给讲成80分，什么事便也都没有了。  

今天，APPLE MUSIC推了“22年音乐回忆”，真是花样一年比一年多，朝着国内的路数奔了。  
听歌总时长13,000分钟，吓一跳，绝大部分是流行乐。  
敢说，这些歌50%不是在安静的环境下听的；90%又不是在理性的状态下听的，剩余10%的理性听完便也失去了。  
音乐实在是毒。  
又被毒害了半个下午。一定戒了流行乐。  

悲伤和兴奋都是罪，罚恐怕早就降了。  
古语典雅，所谓不喜也不悲。  

早时候给有限几位发过《开车》一文，赶上疫情返潮，显得不合时宜。  
心态常给人好的，对这小品文都有积极反馈，可寥寥。  
另外的朋友则一句也不说。我觉得尴尬，似乎不该写。于是后来再没给别人看。  
常做这种事儿，不自觉把氛围就搞僵了，人格有缺陷。只能自己慢体会，慢改。不好指出。  
朋友来消息，应该是心怀感激的，人算是看得起我。  

我自己应该属于另外的朋友。  
甚至更成疾：别人发点什么东西，不行，不像一个世界的，受不了。  
其实原因大概也只是没有一个脚注，造成误会了。  
这些东西里，尤其最痛恨政治宣传，像是从来不踢球却偏要凑热闹来赌球，给人当了枪了。  
关于政治，不深不浅的讨论最要命。  
可这种事情，像是人小时候趁着父母不在对着镜子骂脏话，常伴随无可名状的快感。  

校园，自为的空间难觅。  
俗人甚爱牡丹，学人爱莲，难说会有什么结果。  
周敦颐自称出淤泥不染，实际我敢说未必，文章写得潇洒罢了。  
清风不识字，何必乱翻书。文化的好时代稀有。  

《我这一辈子》的主人公是位巡警，结尾有人对他说了这样一番话：  
“五千年来，中国老百姓糊里糊涂的活着，委委屈屈就死了。  
可是现在不然啦，老百姓要自己当权了。你要给自己站岗啦。”  

石挥57年投海。老舍66年投湖。  
于是究竟怎么个站法？  
文学、电影拦腰斩断，不自觉的枪，把自为的世俗给毙了。  

年轻最是恶。  
今年听得最多的一首《My Back Pages》，23岁的Bob Dylan在歌曲中宣称要告别过去的苍老。  
原来其实年轻人难当。  
把自己的答案跟朋友说，反馈很有意思。  
“你成祥子了。”  
